XCODE_APP="Xcode12.1"

SHOULD_INSTALL_COCOAPODS=true
SHOULD_BOOTSTRAP_CARTHAGE=false

SHOULD_DEPLOY_LIBRARY=false
SHOULD_NEW_DEPLOY_LIBRARY=false
SHOULD_DEPLOY_XCFRAMEWORK=false

PODSPEC_VALIDATION_ALLOWS_WARNINGS=true
SHOULD_VALIDATE_PODSPEC=false

SHOULD_DEPLOY_SOURCE_CODE_TO_GITHUB=true
GITHUB_REPOSITORY_URL="ssh://git@bitbucket.yamoney.ru/~tverdokhleb/github_fake_repo.git"
GITHUB_REPOSITORY_BRANCH_NAME="master"

SCHEME="YooKassaPaymentsDemoApp"
XCODE_WORKSPACE="YooKassaPayments.xcworkspace"
XCODE_PROJECT="YooKassaPaymentsDemoApp.xcodeproj"
XCODE_FRAMEWORK_PROJECT="YooKassaPayments.xcodeproj"

PROVISIONG_PROFILE_SPECIFIER_Debug=""
PROVISIONG_PROFILE_SPECIFIER_AppStore=""
PROVISIONG_PROFILE_SPECIFIER_AdHoc=""

TEAM_ID_Debug="2752592HU5"
TEAM_ID_AdHoc="2752592HU5"
TEAM_ID_AppStore="477EAT77S3"

PROVISION_STYLE_Debug="Automatic"
PROVISION_STYLE_AdHoc="Manual"
PROVISION_STYLE_AppStore="Manual"

CODE_SIGN_IDENTITY_Debug="iPhone Developer"
CODE_SIGN_IDENTITY_AdHoc="iPhone Distribution"
CODE_SIGN_IDENTITY_AppStore="Apple Distribution: \"YooMoney\", NBСO LLC"


PROVISIONG_PROFILE_AdHoc_YooKassaPaymentsDemoApp="YooKassa SDK Payments Example AdHoc"
PROVISIONG_PROFILE_AppStore_YooKassaPaymentsDemoApp="YooKassa SDK Payments Example"

EXPORT_METHOD_Debug="development"
EXPORT_METHOD_AdHoc="ad-hoc"
EXPORT_METHOD_AppStore="app-store"

CARTHAGE_PLATFORMS="iOS"

SLACK_CHANNEL="#ios-builds"
SLACK_BABELYODA_CHANNEL="#b2b-babelyoda"
GITHUB_SLACK_RELEASE_CHANNEL="#github-ios"

BITBUCKET_PROJECT_NAME="MI"
BITBUCKET_REPO_NAME="yandex-checkout-payments-swift"

MINIMUM_COVERAGE_PERCENTAGE="8"
COVERAGE_TARGETS="YooKassaPayments.framework"
